# alembic.ini

# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = migrations

# template used to generate migration files
file_template = %%(rev)s_%%(slug)s

# timezone to use when rendering the date
# within the migration file as well as the filename.
# timezone = UTC

# revision to use as the base for the latest migrations
# (the "head" state).
# revision = head

# If true, the revision will be treated as a "branch point".
# branch = false

# If true, the revision will be treated as a "branch point"
# and the current revision will be recorded as the "down_revision".
# branch = true

# The output encoding used when revision files are written
# output_encoding = utf-8

# sqlalchemy.url = postgresql://user:password@localhost:5432/crm_db

# Usually set via environment variable
# sqlalchemy.url = driver://user:pass@localhost/dbname

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S